echo Running ilmerge...
.\src\TFSBuildNotifier\packages\ILMerge.2.14.1208\tools\ilmerge /out:TfsBuildNotifier.exe src\TfsBuildNotifier\bin\release\TfsBuildNotifier.exe src\TfsBuildNotifier\bin\release\Newtonsoft.Json.dll src\TfsBuildNotifier\bin\release\Hardcodet.Wpf.TaskbarNotification.dll
